### ISSUE TITLE
dovecot22u-2.2.31-1.ius.centos7.x86_64 fails to restart after installing

### ISSUE THREAD

**Issue by fahnoe** [iuscommunity-pkg/dovecot22u#1]
Environment: CentOS Linux release 7.3.1611 

Dovecot RPMs installed:
dovecot22u-2.2.29.1-1.ius.centos7.x86_64
dovecot22u-pigeonhole-2.2.29.1-1.ius.centos7.x86_64

Updating to dovecot22u.x86_64 1:2.2.31-1.ius.centos7 results in the following:

```
touch: cannot touch ‘/var/run/dovecot22u/dovecot22u-restart-after-rpm-install’: No such file or directory
The following updates will be applied on sprite.mpls.fahnoetech.com:
================================================================================
 Package                   Arch       Version                     Repository
                                                                           Size
================================================================================
Updating:
 dovecot22u                x86_64     1:2.2.31-1.ius.centos7      ius     4.2 M
 dovecot22u-pigeonhole     x86_64     1:2.2.31-1.ius.centos7      ius     387 k

Transaction Summary
================================================================================
Upgrade  2 Packages
The updates were successfully applied
```

The dovecot server was shut down by the install but not restarted due to the missing directory.

The issue is due to the new RPM looking for /var/run/dovecot22u while the old RPM used /var/run/dovecot.  

I would prefer to see the ius RPM be consistent with using the dovecot directories & I noticed a related issue with prior RPM creating /etc/pki/dovecot22u while /usr/libexec/dovecot/mkcert.sh and  /etc/dovecot/conf.d/10-ssl.conf were expecting to use /etc/pki/dovecot.  I added a symlink from /etc/pki/dovecot but that's a bit of a hack.

--Larry

**Comment by b-harper** [comment]
Hey @fahnoe,

Thanks for taking the time to submit this issue.  I am surprised we did not catch this issue earlier.  Looks like if you had dovecot installed previously, are upgrading from stock dovecot packages or are not using the default certificates, you would not run into part of this issue.  When initial testing was done, it appears that one or more of these things were a factor.

I have spotted the issue and will work to get updated packages built.

**Comment by fahnoe** [comment]
Hi Ben,

Actually I started with a clean system (no Dovecot from base) and installed dovecot22u-2.2.29.1-1 and dovecot22u-pigeonhole-2.2.29.1-1.  I thought it was odd that there was a discrepancy over the PKI directory the RPM installed to and what the config and script was expecting.  I have not noticed other issues, but I've only just gotten started with Dovecot.

--Larry

**Comment by fahnoe** [comment]
Excellent Ben, many thanks!

--Larry

**Comment by b-harper** [comment]
Updated packages will be hitting the testing repositories after tonight's automation run.

**Comment by b-harper** [comment]
@fahnoe,

I wanted to see if you could test these new packages and if they work for you.

**Comment by fahnoe** [comment]
Hi Ben, sorry, I was waiting for the packages to show up in the live repos.

I just installed out of testing and dovecot was properly restarted, so my original issue is resolved.

Since you also addressed the issue of /etc/pki/dovecot22u, I had renamed that directory to /etc/pki/dovecot.  Upon installing the update, I got the following warnings which I would think would be expected in this circumstance:

warning: file /etc/pki/dovecot22u/private: remove failed: No such file or directory
warning: file /etc/pki/dovecot22u/dovecot-openssl.cnf: remove failed: No such file or directory
warning: file /etc/pki/dovecot22u/certs: remove failed: No such file or directory
warning: file /etc/pki/dovecot22u: remove failed: No such file or directory

--Larry

**Comment by b-harper** [comment]
Hey @fahnoe,

Thanks for the reply.  That sort of output should be excepted if yum was attempting to remove files that you had already moved.  Seeing that the updated packages fixed your issue, I will go ahead and push them into the stable repositories during tonight's automation.
