### ISSUE TITLE
Update to 2.2.36

### ISSUE THREAD

**Issue by fraenki** [iuscommunity-pkg/dovecot22u#2]
The package is currently at version 2.2.35. Do you plan to update it to 2.2.36?
I'm asking because 2.2.36 may be the final release in the 2.2 series:
https://www.dovecot.org/list/dovecot-news/2018-May/000379.html

**Comment by carlwgeorge** [comment]
Yes, it's in the backlog.  If you would like to move it along please send a pull request and I'll review it.  Otherwise, I'll get to it myself eventually.

**Comment by carlwgeorge** [comment]
This was fixed back in December.

https://github.com/iuscommunity-pkg/dovecot22u/releases/tag/2.2.36-1
